Curso_Django/urls.py
from django.contrib import admin
from django.urls import path, include
from inventario.views import index

urlpatterns = [
    path("admin/", admin.site.urls),
    path('inventario/', include('inventario.urls')),
    path('', index, name='index'),
    path('ventas/', include('ventas.urls'))
]

inventario/urls.py
from django.urls import path
from . import views

app_name = 'inventario'

urlpatterns = [
    path('productos/', views.productos_disponibles, name='productos_disponibles'),
    path('crear/', views.crear_producto, name='crear_producto'),
    path('editar/<int:pk>/', views.editar_producto, name='editar_producto'),
    path('eliminar/<int:pk>/', views.eliminar_producto, name='eliminar_producto'),
]

ventas/urls.py
from django.urls import path
from . import views

app_name ='ventas'

urlpatterns = [
    path('clientes/', views.listado_clientes, name='listado_cliente'),
    path('clientes/crear/', views.crear_cliente, name='crear_cliente'),
    path('crear/<int:cliente_id>/', views.crear_venta, name='crear_venta'),
    path('', views.listado_ventas, name='listado_ventas')
    
]

inventario/models.py
from django.db import models

# Create your models here.
class Categoria (models.Model):
    nombre = models.CharField(max_length=100)

    def __str__(self):
        return self.nombre

class Producto(models.Model):
    nombre = models.CharField(max_length=100)
    precio = models.DecimalField(max_digits=10, decimal_places=2)
    stock = models.PositiveIntegerField()
    categoria = models.ForeignKey(Categoria, on_delete=models.CASCADE)

    def __str__(self):
        return self.nombre

class MovimientoStock(models.Model):
    producto = models.ForeignKey(Producto, on_delete=models.CASCADE)
    fecha = models.DateField(auto_now_add=True)
    tipo = models.CharField(max_length=10)
    cantidad = models.IntegerField()
    descripcion = models.TextField(blank=True, null=True)

    def __str__(self):
        return f"{self.tipo} de {self.cantidad} - {self.producto.nombre}"

ventas/models.py
from django.db import models
from inventario.models import Producto

# Create your models here.
class Cliente(models.Model):
    nombre = models.CharField(max_length=150)

class Venta(models.Model):
    cliente = models.ForeignKey(Cliente, on_delete=models.CASCADE)
    fecha = models.DateTimeField(auto_now_add=True)

class ItemVenta(models.Model):
    venta = models.ForeignKey(Venta, on_delete=models.CASCADE)
    producto = models.ForeignKey(Producto, on_delete=models.CASCADE)
    cantidad = models.PositiveIntegerField()
    precio_unitario = models.DecimalField(max_digits=10, decimal_places=2)

inventario/forms.py
from django import forms
from .models import Producto

class ProductoForm(forms.ModelForm):
    class Meta:
        model = Producto
        fields = ['nombre', 'precio', 'stock', 'categoria']

ventas/forms.py
from django import forms
from .models import Cliente, ItemVenta

class ClienteForm(forms.ModelForm):
    class Meta:
        model = Cliente
        fields =['nombre']


class ItemVentaForm(forms.ModelForm):
    class Meta:
        model = ItemVenta
        fields = ['producto', 'cantidad', 'precio_unitario']

inventario/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Producto
from .forms import ProductoForm

# Create your views here.
def productos_disponibles(request):
    productos = Producto.objects.filter(stock__gt=0)
    return render(request, 'inventario/productos.html', {'productos': productos})

def crear_producto(request):
    form = ProductoForm(request.POST or None)
    if form.is_valid():
        form.save()
        return redirect('inventario:productos_disponibles')
    return render(request, 'inventario/formulario_producto.html', {'form': form})

def editar_producto(request, pk):
    producto  = get_object_or_404(Producto, pk=pk)
    form = ProductoForm(request.POST or None, instance=producto)
    if form.is_valid():
        form.save()
        return redirect('inventario:productos_disponibles')
    return render(request, 'inventario/formulario_producto.html', {'form': form})

def eliminar_producto(request, pk):
    producto = get_object_or_404(Producto, pk=pk)
    if request.method == 'POST':
        producto.delete()
        return redirect('inventario:productos_disponibles')
    return render(request, 'inventario/confirmar_eliminar.html', {'producto': producto})
    
def index(request):
    return render(request, 'base.html')

ventas/views.py
from django.shortcuts import render, redirect,get_object_or_404
from .models import Cliente, Venta, ItemVenta
from .forms import ClienteForm, ItemVentaForm
from django.utils import timezone

def crear_cliente(request):
    if request.method == 'POST':
        form = ClienteForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('ventas:listado_cliente')
    else:
        form = ClienteForm()
    return render(request, 'ventas/formulario_cliente.html', {'form': form} )

def listado_clientes(request):
    clientes = Cliente.objects.all()
    return render(request, 'ventas/listado_clientes.html', {'clientes': clientes})

def crear_venta(request, cliente_id):
    cliente = get_object_or_404(Cliente, pk=cliente_id)
    if request.method == 'POST':
        form = ItemVentaForm(request.POST)
        if form.is_valid():
            venta = Venta.objects.create(cliente=cliente, fecha=timezone.now())
            item = form.save(commit=False)
            item.venta = venta
            item.save()
            return redirect('ventas:listado_ventas')
    else:
        form= ItemVentaForm()
    return render(request, 'ventas/crear_venta.html', {'form': form, 'cliente':cliente} )

def listado_ventas(request):
    ventas = Venta.objects.all()
    return render(request, 'ventas/listado_ventas.html', {'ventas': ventas})

templates/base.html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Sistema de Gestión{% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
</head>
<body>
    <div class="container mt-4">
        <h1 class="mb-4">Sistema de Ventas e Inventario</h1>
        <div class="mb-4">
            <a href="{% url 'inventario:productos_disponibles' %}" class="btn btn-outline-primary">Stock de Productos</a>
            <a href="{% url 'inventario:crear_producto' %}" class="btn btn-outline-primary">Crear Producto</a>
            <a href="{% url 'ventas:listado_cliente' %}" class="btn btn-outline-primary">Clientes</a>
            <a href="{% url 'ventas:crear_cliente' %}" class="btn btn-outline-primary">Crear Cliente</a>
            <a href="{% url 'ventas:listado_ventas' %}" class="btn btn-outline-primary">Ventas</a>
        </div>
        {% block content %}<h2>ESTA ES LA BASE DEL PROYECTO</h2>{% endblock %}
    </div>
</body>
</html>

templates/inventario/confirmar_eliminar.html
{% extends "base.html" %}

{% block title %}
Eliminar Producto
{% endblock title %}

{% block content %}


<h2> Estas seguro de querer eliminar el producto "{{ producto.nombre }}"</h2>


<form method="post">
    {% csrf_token %}
    <button type="submit" class="btn btn-danger">Si, eliminar</button>
</form>

{% endblock content %}

templates/inventario/formulario_producto.html
{% extends 'base.html'%}

{% block title %}
Formulario Productos
{% endblock title %}


{% block content %}


<h2>{% if form.instance.pk %} Editar {% else %} Crear {% endif %} </h2>

<form method="post">
    {% csrf_token %}
    {{ form.as_p}}
    <button type="submit" class="btn btn-primary">Guardar</button>
</form>

{% endblock content %}

templates/inventario/productos.html
{% extends "base.html" %}

{% block title %}
Productos Disponible
{% endblock title %}

{% block content %}

<h2>Productos disponibles</h2>
<table class="table table-bordered">
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Precio</th>
      <th>Stock</th>
      <th>Categoría</th>
      <th>Acciones</th>
    </tr>
  </thead>
  <tbody>
    {% for producto in productos %}
    <tr>
      <td>{{ producto.nombre }}</td>
      <td>${{ producto.precio }}</td>
      <td>{{ producto.stock }}</td>
      <td>{{ producto.categoria.nombre }}</td>
      <td>
        <a href="{% url 'inventario:editar_producto' producto.id %}" class="btn btn-sm btn-warning">Editar</a>
        <a href="{% url 'inventario:eliminar_producto' producto.id %}" class="btn btn-sm btn-danger">Eliminar</a>
        

      </td>



    </tr>
    {% endfor %}
  </tbody>
</table>







{% endblock content %}

templates/ventas/crear_venta.html
{% extends "base.html" %}

{% block title %}
Crear Venta
{% endblock title %}

{% block content %}

<h2>Nueva Venta para {{ cliente.nombre }}</h2>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-success">Registrar Venta</button>
</form>


{% endblock content %}

templates/ventas/formulario_cliente.html
{% extends "base.html" %}

{% block title %}
Formulario Clientes
{% endblock title %}

{% block content %}

<h2> Formulario de Cliente</h2>

<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-primary">Guardar</button>
</form>


{% endblock content %}

templates/ventas/listado_clientes.html
{% extends "base.html" %}

{% block title %}
Listado Cliente
{% endblock title %}

{% block content %}

<h2>Clientes</h2>
<table class="table table-bordered">
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Acciones</th>
   
    </tr>
  </thead>
  <tbody>
    {% for cliente in clientes %}
    <tr>
      <td>{{ cliente.nombre }}</td>
      <td> <a href="{% url 'ventas:crear_venta' cliente.id %}" class="btn btn-sm btn-primary"> Crear Venta</a></td>


    </tr>
    {% endfor %}
  </tbody>
</table>







{% endblock content %}

templates/ventas/listado_ventas.html
{% extends "base.html" %}

{% block title %}
Listado Venta
{% endblock title %}

{% block content %}

<h2>Ventas</h2>
<table class="table table-bordered">
  <thead>
    <tr>
      <th>Cliente</th>
      <th>Fecha</th>
   
    </tr>
  </thead>
  <tbody>
    {% for venta in ventas %}
    <tr>
      <td>{{ venta.cliente.nombre }}</td>
      <td>{{ venta.fecha }}</td>
  


    </tr>
    {% endfor %}
  </tbody>
</table>

{% endblock content %}